"""add track file_mtime_ns

Revision ID: 41fed9c54ddb
Revises: 7159e92fa59d
Create Date: 2026-10-07 19:27:46.334388

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41fed9c54ddb"
down_revision: Union[str, Sequence[str], None] = "7159e92fa59d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("file_mtime_ns", sa.Integer(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.drop_column("file_mtime_ns")

    # ### end Alembic commands ###
