"""baseline

The schema as it stands before anyone else has a copy of it.

`create_all` adds a missing table and never alters an existing one, so
without a chain of revisions the first release that adds a column would
leave every installed database on the old schema, answering `no such
column` to the first query that asked for it. Re-scanning instead would
cost the user their stored hashes, their fingerprints and their format
order, which is not a repair.

This revision creates the tables rather than describing them, so a
database that already has them must be stamped with this id, not upgraded
to it.

`downgrade` drops all three tables, which on an installed copy is the
user's entire library. Nothing in the application may call it.

Revision ID: 7159e92fa59d
Revises:
Create Date: 2026-10-03 18:58:10.483717

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7159e92fa59d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("root_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_scanned_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_collection_name"), ["name"], unique=True)

    op.create_table(
        "formatorderrow",
        sa.Column("format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("format"),
    )
    op.create_table(
        "track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("artist", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("album", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("format", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bit_depth", sa.Integer(), nullable=True),
        sa.Column("bit_rate", sa.Integer(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fingerprint", sa.LargeBinary(), nullable=True),
        sa.Column("fingerprint_algorithm", sa.Integer(), nullable=True),
        sa.Column("fingerprint_length", sa.Integer(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "file_path"),
    )
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_track_file_path"), ["file_path"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_file_path"))

    op.drop_table("track")
    op.drop_table("formatorderrow")
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collection_name"))

    op.drop_table("collection")
    # ### end Alembic commands ###
